# Generated by Django 3.2.13 on 2022-05-26 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acronimo',
            fields=[
                ('idAcronimo', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idAcronimo')),
                ('Sigla', models.CharField(max_length=15)),
                ('Descripcion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'Acronimo',
            },
        ),
        migrations.CreateModel(
            name='AguaCemento',
            fields=[
                ('idAguaCem', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idAguaCem')),
                ('relacionAc', models.CharField(max_length=5)),
                ('fk_Acronimo', models.ForeignKey(db_column='fk_Acronimo', on_delete=django.db.models.deletion.CASCADE, to='quickstart.acronimo', verbose_name='Acronimo')),
            ],
            options={
                'db_table': 'AguaCemento',
            },
        ),
        migrations.CreateModel(
            name='AplPrincipales',
            fields=[
                ('idAplPrinc', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idAplPrinc')),
                ('aplicaciones', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'AplPrincipales',
            },
        ),
        migrations.CreateModel(
            name='ClasExposicion',
            fields=[
                ('idClasExpo', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idClasExpo')),
                ('Categoria', models.CharField(max_length=60)),
                ('Condicion', models.CharField(max_length=600)),
                ('Clase', models.CharField(max_length=2)),
                ('fk_AguaCem', models.ForeignKey(db_column='fk_AguaCem', on_delete=django.db.models.deletion.CASCADE, to='quickstart.aguacemento', verbose_name='Agua Cemento')),
            ],
            options={
                'db_table': 'ClasExposicion',
            },
        ),
        migrations.CreateModel(
            name='Esfuerzo',
            fields=[
                ('idEsfuerzo', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idEsfuerzo')),
                ('tipoEsfuerzo', models.CharField(max_length=50)),
                ('fk_Acronimo', models.ForeignKey(db_column='fk_Acronimo', on_delete=django.db.models.deletion.CASCADE, to='quickstart.acronimo', verbose_name='Acronimo')),
            ],
            options={
                'db_table': 'Esfuerzo',
            },
        ),
        migrations.CreateModel(
            name='FibraConcre',
            fields=[
                ('idFibraCon', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idFibraCon')),
                ('Tipo', models.CharField(max_length=20)),
                ('tipoMaterial', models.CharField(max_length=20)),
                ('Fibras', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'FibraConcre',
            },
        ),
        migrations.CreateModel(
            name='IonCloruro',
            fields=[
                ('idIonClor', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idIonClor')),
                ('cargaPesada', models.CharField(max_length=15)),
                ('tipoPenet', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'IonCloruro',
            },
        ),
        migrations.CreateModel(
            name='OMC23Nivel1',
            fields=[
                ('idOmc23N1', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc23N1')),
                ('Codigo', models.CharField(max_length=10)),
                ('descriEng', models.CharField(max_length=100)),
                ('descriSpa', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Omc23Nivel1',
            },
        ),
        migrations.CreateModel(
            name='OMC23Nivel2',
            fields=[
                ('idOmc23N2', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc23N2')),
                ('Codigo', models.CharField(max_length=10)),
                ('descriEng', models.CharField(max_length=100)),
                ('descriSpa', models.CharField(blank=True, max_length=110, null=True)),
                ('fk_Omc23N1', models.ForeignKey(db_column='fk_Omc23N1', on_delete=django.db.models.deletion.CASCADE, to='quickstart.omc23nivel1', verbose_name='Nivel 1')),
            ],
            options={
                'db_table': 'Omc23Nivel2',
            },
        ),
        migrations.CreateModel(
            name='OMC23Nivel3',
            fields=[
                ('idOmc23N3', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc23N3')),
                ('Codigo', models.CharField(max_length=10)),
                ('descriEng', models.CharField(max_length=100)),
                ('descriSpa', models.CharField(blank=True, max_length=100, null=True)),
                ('fk_Omc23N2', models.ForeignKey(db_column='fk_Omc23N2', on_delete=django.db.models.deletion.CASCADE, to='quickstart.omc23nivel2', verbose_name='Nivel 2')),
            ],
            options={
                'db_table': 'Omc23Nivel3',
            },
        ),
        migrations.CreateModel(
            name='OMC23Nivel4',
            fields=[
                ('idOmc23N4', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc23N4')),
                ('Codigo', models.CharField(max_length=15)),
                ('descriEng', models.CharField(max_length=100)),
                ('descriSpa', models.CharField(blank=True, max_length=110, null=True)),
                ('fk_Omc23N3', models.ForeignKey(db_column='fk_Omc23N3', on_delete=django.db.models.deletion.CASCADE, to='quickstart.omc23nivel3', verbose_name='Nivel 3')),
            ],
            options={
                'db_table': 'Omc23Nivel4',
            },
        ),
        migrations.CreateModel(
            name='OMC23Nivel5',
            fields=[
                ('idOmc23N5', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc23N5')),
                ('Codigo', models.CharField(max_length=15)),
                ('descriEng', models.CharField(max_length=120)),
                ('descriSpa', models.CharField(blank=True, max_length=120, null=True)),
                ('fk_Omc23N4', models.ForeignKey(db_column='fk_Omc23N4', on_delete=django.db.models.deletion.CASCADE, to='quickstart.omc23nivel4', verbose_name='Nivel 4')),
            ],
            options={
                'db_table': 'Omc23Nivel5',
            },
        ),
        migrations.CreateModel(
            name='OmniClass23',
            fields=[
                ('idOmc23', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc23')),
                ('numMat', models.IntegerField()),
                ('Codigo', models.CharField(max_length=18)),
                ('descriEng', models.CharField(blank=True, max_length=120, null=True)),
                ('descriSpa', models.CharField(blank=True, max_length=120, null=True)),
                ('Nivel', models.IntegerField()),
                ('regFinal', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Omniclass23',
            },
        ),
        migrations.CreateModel(
            name='OmniClass41',
            fields=[
                ('idOmc41', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc41')),
                ('numMat', models.IntegerField()),
                ('Codigo', models.CharField(max_length=15)),
                ('descriEng', models.CharField(max_length=50)),
                ('descriSpa', models.CharField(blank=True, max_length=55, null=True)),
                ('Nivel', models.IntegerField()),
                ('regFinal', models.BooleanField(blank=True)),
            ],
            options={
                'db_table': 'Omniclass41',
            },
        ),
        migrations.CreateModel(
            name='SistColocacion',
            fields=[
                ('idSistColoc', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idSistColoc')),
                ('tipoSistema', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'SistColocacion',
            },
        ),
        migrations.CreateModel(
            name='TipoConsistencia',
            fields=[
                ('idTipoCons', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idTipoCons')),
                ('Tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'TipoConsistencia',
            },
        ),
        migrations.CreateModel(
            name='TipoResistencia',
            fields=[
                ('idTipoResist', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idTipoResist')),
                ('Tipo', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'TipoResistencia',
            },
        ),
        migrations.CreateModel(
            name='TipoUniMed',
            fields=[
                ('idTipMed', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idTipMed')),
                ('Tipo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'TipoUniMed',
            },
        ),
        migrations.CreateModel(
            name='UnidadesMedida',
            fields=[
                ('idUniMed', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idUniMed')),
                ('Unidad', models.CharField(max_length=15)),
                ('Descripcion', models.CharField(max_length=80)),
                ('Sistema', models.CharField(blank=True, max_length=30, null=True)),
                ('fk_TipUniMed', models.ForeignKey(blank=True, db_column='fk_TipUniMed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.tipounimed', verbose_name='Tipo Unidad Medida')),
            ],
            options={
                'db_table': 'UnidadesMedida',
            },
        ),
        migrations.CreateModel(
            name='ValorEsfuerzo',
            fields=[
                ('idValEsf', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idValEsf')),
                ('Valor', models.FloatField()),
                ('fk_Esfuerzo', models.ForeignKey(db_column='fk_Esfuerzo', on_delete=django.db.models.deletion.CASCADE, to='quickstart.esfuerzo', verbose_name='Esfuerzo')),
                ('fk_TipoResist', models.ForeignKey(blank=True, db_column='fk_TipoResist', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.tiporesistencia')),
                ('fk_UniMed', models.ForeignKey(db_column='fk_UniMed', on_delete=django.db.models.deletion.CASCADE, to='quickstart.unidadesmedida', verbose_name='Unidad Medida')),
            ],
            options={
                'db_table': 'ValorEsfuerzo',
            },
        ),
        migrations.CreateModel(
            name='TMA',
            fields=[
                ('idTma', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idTma')),
                ('valTma', models.CharField(max_length=5)),
                ('tmaFrac', models.CharField(blank=True, max_length=8, null=True)),
                ('fk_Acronimo', models.ForeignKey(blank=True, db_column='fk_Acronimo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.acronimo', verbose_name='Acronimo')),
                ('fk_UniMed', models.ForeignKey(db_column='fk_UniMed', on_delete=django.db.models.deletion.CASCADE, to='quickstart.unidadesmedida', verbose_name='Unidad Medida')),
            ],
            options={
                'db_table': 'TMA',
            },
        ),
        migrations.CreateModel(
            name='Revenimiento',
            fields=[
                ('idReven', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idReven')),
                ('valRev', models.CharField(max_length=10)),
                ('fk_Acronimo', models.ForeignKey(db_column='fk_Acronimo', on_delete=django.db.models.deletion.CASCADE, to='quickstart.acronimo', verbose_name='Acronimo')),
                ('fk_TipoCons', models.ForeignKey(blank=True, db_column='fk_TipoCons', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.tipoconsistencia', verbose_name='Tipo Consistencia')),
                ('fk_UniMed', models.ForeignKey(db_column='fk_UniMed', on_delete=django.db.models.deletion.CASCADE, to='quickstart.unidadesmedida', verbose_name='Unidad Medida')),
            ],
            options={
                'db_table': 'Revenimiento',
            },
        ),
        migrations.CreateModel(
            name='OMC23Nivel6',
            fields=[
                ('idOmc23N6', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc23N6')),
                ('Codigo', models.CharField(max_length=18)),
                ('descriEng', models.CharField(max_length=100)),
                ('descriSpa', models.CharField(blank=True, max_length=100, null=True)),
                ('fk_Omc23N5', models.ForeignKey(db_column='fk_Omc23N5', on_delete=django.db.models.deletion.CASCADE, to='quickstart.omc23nivel5', verbose_name='Nivel 5')),
            ],
            options={
                'db_table': 'Omc23Nivel6',
            },
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('idMaterial', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idMaterial')),
                ('numMat', models.IntegerField()),
                ('codigoOmc', models.CharField(max_length=18)),
                ('Consecutivo', models.CharField(blank=True, max_length=5, null=True)),
                ('descriCorta', models.CharField(blank=True, max_length=100, null=True)),
                ('descriLarga', models.TextField(blank=True, null=True)),
                ('Comentarios', models.CharField(blank=True, max_length=200, null=True)),
                ('palabrasCve', models.CharField(blank=True, max_length=45, null=True)),
                ('codigoBimsa', models.CharField(blank=True, max_length=15, null=True)),
                ('fk_Omc23', models.ForeignKey(blank=True, db_column='fk_Omc23', null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.omniclass23', verbose_name='OMNICLASS23')),
                ('fk_Omc41', models.ForeignKey(blank=True, db_column='fk_Omc41', null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.omniclass41', verbose_name='OMNICLASS41')),
            ],
            options={
                'db_table': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='FlujoRev',
            fields=[
                ('idFlujoRev', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idFlujoRev')),
                ('valFluRev', models.FloatField()),
                ('fk_UniMed', models.ForeignKey(db_column='fk_UniMed', on_delete=django.db.models.deletion.CASCADE, to='quickstart.unidadesmedida', verbose_name='Unidad Medida')),
            ],
            options={
                'db_table': 'FlujoRev',
            },
        ),
        migrations.CreateModel(
            name='Densidad',
            fields=[
                ('idDensidad', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idDensidad')),
                ('denRelativa', models.FloatField(blank=True, null=True)),
                ('denRelatAparent', models.FloatField(blank=True, null=True)),
                ('valDensidad', models.FloatField()),
                ('denAparente', models.FloatField(blank=True, null=True)),
                ('unidadPeso', models.FloatField(blank=True, null=True)),
                ('unidadPesoSss', models.FloatField(blank=True, null=True)),
                ('fk_UniMed', models.ForeignKey(db_column='fk_UniMed', on_delete=django.db.models.deletion.CASCADE, to='quickstart.unidadesmedida', verbose_name='Unidad Medida')),
            ],
            options={
                'db_table': 'Densidad',
            },
        ),
        migrations.CreateModel(
            name='Concreto',
            fields=[
                ('idConcreto', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idConcreto')),
                ('numMat', models.IntegerField()),
                ('Codigo', models.CharField(max_length=18)),
                ('fk_AplPrinc', models.ForeignKey(blank=True, db_column='fk_AplPrinc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.aplprincipales', verbose_name='Aplicaciones Principales')),
                ('fk_ClasExpo', models.ForeignKey(blank=True, db_column='fk_ClasExpo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.clasexposicion', verbose_name='Clase Exposicion')),
                ('fk_Densidad', models.ForeignKey(blank=True, db_column='fk_Densidad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.densidad', verbose_name='Densidad')),
                ('fk_FibraConcre', models.ForeignKey(blank=True, db_column='fk_FibraConcre', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.fibraconcre', verbose_name='Fibra')),
                ('fk_FlujoRev', models.ForeignKey(blank=True, db_column='fk_FlujoRev', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.flujorev', verbose_name='Flujo Revenimiento')),
                ('fk_Material', models.ForeignKey(db_column='fk_Material', on_delete=django.db.models.deletion.CASCADE, to='quickstart.materiales', verbose_name='Materiales')),
                ('fk_Reven', models.ForeignKey(db_column='fk_Reven', on_delete=django.db.models.deletion.CASCADE, to='quickstart.revenimiento', verbose_name='Revenimiento')),
                ('fk_SistColoc', models.ForeignKey(db_column='fk_SistColoc', on_delete=django.db.models.deletion.CASCADE, to='quickstart.sistcolocacion', verbose_name='Sistema Colocacion')),
                ('fk_Tma', models.ForeignKey(db_column='fk_Tma', on_delete=django.db.models.deletion.CASCADE, to='quickstart.tma', verbose_name='TMA')),
                ('fk_ValEsf', models.ForeignKey(db_column='fk_ValEsf', on_delete=django.db.models.deletion.CASCADE, to='quickstart.valoresfuerzo', verbose_name='Valor Esfuerzo')),
            ],
            options={
                'db_table': 'Concreto',
            },
        ),
        migrations.AddField(
            model_name='clasexposicion',
            name='fk_ValEsf',
            field=models.ForeignKey(db_column='fk_ValEsf', on_delete=django.db.models.deletion.CASCADE, to='quickstart.valoresfuerzo', verbose_name='Valor Esfuerzo'),
        ),
        migrations.CreateModel(
            name='CaracEspe',
            fields=[
                ('idCaracEspec', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idCaracEspec')),
                ('modElast', models.FloatField(blank=True, null=True)),
                ('Acronimo', models.CharField(blank=True, max_length=3, null=True)),
                ('Edad', models.FloatField(blank=True, null=True)),
                ('absorcionCap', models.FloatField(blank=True, null=True)),
                ('Acronimo2', models.CharField(blank=True, max_length=3, null=True)),
                ('trabaExtend', models.FloatField(blank=True, null=True)),
                ('Clase', models.CharField(blank=True, max_length=10, null=True)),
                ('Color', models.CharField(blank=True, max_length=10, null=True)),
                ('Comportamiento', models.CharField(blank=True, max_length=30, null=True)),
                ('conAire', models.FloatField(blank=True, null=True)),
                ('conIonClor', models.FloatField(blank=True, null=True)),
                ('tiempoPrueba', models.FloatField(blank=True, null=True)),
                ('fk_Concreto', models.ForeignKey(blank=True, db_column='fk_Concreto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.concreto', verbose_name='Concreto')),
                ('fk_IonClor', models.ForeignKey(blank=True, db_column='fk_IonClor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.ioncloruro', verbose_name='Ion Cloruro')),
            ],
            options={
                'db_table': 'CaracEspe',
            },
        ),
    ]
